sensor_kit_base_link:
  traffic_light_left_camera/camera_link:
    x: 0.103
    y: 0.0
    z: -0.119
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  velodyne_left_base_link:
    x: -0.3997
    y: 0.479
    z: -0.0456
    roll: -0.610865
    
    pitch: 0.0
    yaw: 0.0
  velodyne_right_base_link:
    x: -0.399
    y: -0.4784
    z: -0.0464
    roll: 0.610865
    pitch: 0.0
    yaw: 0.0
  gnss_link:
    x: -0.755
    y: -0.312
    z: -0.027
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: -0.755
    y: -0.312
    z: -0.027
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
